---
version: "3"

services:
    flask-app:
        build:
            context: ./
            dockerfile: ./Dockerfile
        image: nicoleolv/flask-iss-tracker:1.0
        container_name: flask-iss-tracker-app
        ports:
            - "5000:5000"
...